# Generated by Django 5.1.7 on 2025-03-18 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "houses",
            "0002_rename_not_completed_task_count_house_not_completed_tasks_count",
        ),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="houses.house",
            ),
        ),
    ]
