# Generated by Django 5.1.7 on 2025-03-18 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="house",
            old_name="not_completed_task_count",
            new_name="not_completed_tasks_count",
        ),
    ]
